# Generated by Django 4.2.8 on 2024-12-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fullname',
            new_name='name',
        ),
    ]
